# Generated by Django 3.2 on 2023-01-29 20:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='Long description')),
                ('short_description', models.TextField(blank=True, verbose_name='Short description')),
                ('longitude', models.FloatField(null=True, unique=True)),
                ('latitude', models.FloatField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='images/', verbose_name='Image')),
                ('image_order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='place')),
            ],
            options={
                'ordering': ['image_order'],
            },
        ),
    ]
