# Generated by Django 3.2.16 on 2023-01-19 14:06
import json
import os

from django.db import migrations


class Migration(migrations.Migration):

    def load_places(self, schema_editor):
        Place = self.get_model('places', 'Place')
        file_paths = []
        for file in os.listdir("static/places"):
            if file.endswith(".json"):
                file_paths.append(os.path.join("static/places", file))

        for file in file_paths:
            with open(file, "r", encoding="utf-8") as place:
                Place.objects.get_or_create(title=json.load(place)['title'])

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_places, migrations.RunPython.noop)
    ]
