# Generated by Django 4.0 on 2023-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
