# Generated by Django 3.2 on 2023-01-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
