# Generated by Django 4.0 on 2023-01-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
