# Generated by Django 4.0 on 2023-01-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_image_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image', 'place')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'short_description', 'long_description')},
        ),
    ]
