# Generated by Django 3.2.16 on 2023-01-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
