# Generated by Django 4.1.5 on 2023-01-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
