# Generated by Django 4.1.5 on 2023-01-28 00:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_options_alter_image_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.PositiveIntegerField(db_index=True, default=0, primary_key=True, serialize=False),
        ),
    ]
