# Generated by Django 4.0 on 2023-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_place_content_alter_place_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.PositiveIntegerField(db_index=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
